version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=kittytracker
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh

  postgres:
    image: postgres
    volumes:
      - ${PWD}/.db/kittytracker/postgres:/var/lib/postgresql/data
      - ${PWD}/.db/kittytracker/postgres-backups:/backups
    environment:
      - POSTGRES_USER=kittytracker


